d /run/monutchee       0770 root   msap1-data -
d /run/monutchee/nginx 0750 worker worker     -
d /var/lib/monutchee     0755 root   root       -
d /var/lib/monutchee/tls 0750 worker worker     -
d /data/mnc              0770 root   msap1-data -
d /data/mnc/waveform     0770 root   msap1-data -
d /data/mnc/settings     0700 msap1-settings msap1-settings -
d /data/mnc/database                   0710 root             msap1-data -
d /data/mnc/database/meter-stream      0700 msap1-stream     msap1-data -
d /data/mnc/database/meter-historian   0700 msap1-historian  msap1-data -
