# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
KRIA_ADDON_LAYERDIR := "${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "kria-addon"
BBFILE_PATTERN_kria-addon = "^${LAYERDIR}/"
BBFILE_PRIORITY_kria-addon = "5"

LAYERDEPENDS_kria-addon = "core kria"
LAYERSERIES_COMPAT_kria-addon = "scarthgap"

require conf/kria-qspi-workaround.inc
