#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
export PATH=/bin
fail() { echo 'Cannot mount immutable RAM root' >/dev/console; exec sh </dev/console >/dev/console 2>&1; }
mount -t devtmpfs devtmpfs /dev || fail
mount -t proc proc /proc || fail
mount -t sysfs sysfs /sys || fail
mount -t tmpfs -o mode=0755,nosuid,nodev tmpfs /run || fail
mkdir -p @MNC_BOOT_ROOT@ || fail
mv /rootfs.squashfs @MNC_BOOT_ROOT@/rootfs.squashfs || fail
mount -t squashfs -o loop,ro @MNC_BOOT_ROOT@/rootfs.squashfs /newroot || fail
mount --move /dev /newroot/dev || fail
mount --move /proc /newroot/proc || fail
mount --move /sys /newroot/sys || fail
mount --move /run /newroot/run || fail
exec switch_root /newroot /sbin/mnc-storage-init
