// SPDX-License-Identifier: GPL-3.0-only
#include "network_config.hpp"
#include <sstream>
namespace mnc::os::system {
std::string renderNetwork(const mnc::system::NetworkConfig &c,
                          bool hasPreferred) {
  using namespace mnc::system;
  validateNetwork({c});
  std::ostringstream f;
  f << "# Generated by MNC System Manager\n[Match]\nName="
    << c.interface << "\n\n[Network]\nDHCP="
    << (c.mode == NetworkMode::dhcp ? "yes" : "no") << "\nIPv6AcceptRA=yes\n";
  if (c.mode == NetworkMode::static_ipv4)
    f << "Address=" << c.address << '/'
      << static_cast<unsigned>(c.prefix_length) << '\n';
  for (const auto &dns : c.dns_servers)
    f << "DNS=" << dns << '\n';
  const unsigned metric = c.preferred_default ? 100 : 600;
  if (c.mode == NetworkMode::static_ipv4 && !c.gateway.empty()) {
    f << "\n[Route]\nGateway=" << c.gateway << '\n';
    if (hasPreferred)
      f << "Metric=" << metric << '\n';
  }
  for (const auto *section : {"DHCPv4", "DHCPv6", "IPv6AcceptRA"}) {
    f << "\n[" << section
      << "]\nUseDNS=" << (c.dns_servers.empty() ? "yes" : "no") << '\n';
    if (std::string_view(section) == "DHCPv4")
      f << "UseDomains=yes\n";
    // DHCPv6 supplies addresses; IPv6 default routes come from RA.
    if (hasPreferred && std::string_view(section) != "DHCPv6")
      f << "RouteMetric=" << metric << '\n';
  }
  return f.str();
}
} // namespace mnc::os::system
