# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
XILINX_ADDON_LAYERDIR := "${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xilinx-addon"
BBFILE_PATTERN_xilinx-addon = "^${LAYERDIR}/"
BBFILE_PRIORITY_xilinx-addon = "5"

LAYERDEPENDS_xilinx-addon = "core xilinx"
LAYERSERIES_COMPAT_xilinx-addon = "scarthgap"

# Xilinx-common build settings shared by every Xilinx product.
require conf/xilinx-build.inc
