# We have a conf and classes directory, add to BBPATH.
BBPATH .= ":${LAYERDIR}"
MSAP1_LAYERDIR := "${LAYERDIR}"

# We have recipes-* directories, add to BBFILES.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-msap1"
BBFILE_PATTERN_meta-msap1 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-msap1 = "6"

LAYERDEPENDS_meta-msap1 = " \
    core \
    mncos \
    xilinx-addon \
    zynqmp-addon \
    kria-addon \
    kria \
    xilinx \
    xilinx-standalone \
    "
LAYERSERIES_COMPAT_meta-msap1 = "scarthgap"

PROJECT_NAME ?= "msap1"

require conf/kria-bootcmd-usb-rootfs-partuuid.inc
